// base
const BASE_LOADING = "BASE_LOADING"

// junshi
const FETCH_JUNSHI = "FETCH_JUNSHI"
const RECEIVE_JUNSHI = "RECEIVE_JUNSHI"

module.exports = {
  BASE_LOADING,
  FETCH_JUNSHI,
  RECEIVE_JUNSHI,
}
