module.exports = {
  IOS_MOZI_KEY: 'U2FsdGVkX18cpkVER23U5PNi5PBX5KLA/h6yGesmEE4=', // 小黑IOS
  ANDROID_MOZI_DKEY: 'U2FsdGVkX19pGXJl7rtdgVE3LmSvRIYQ6Ku+dmEkDHo=', // 小黑ANDROID
  LOGIN_KEY: 'isLogIn',
};
